default: &default
   host: localhost
   adapter: mysql2
   encoding: utf8
   reconnect: false
   pool: 5
   username: crm
   password: crm

development:
   <<: *default
   database: crm

production:
  <<: *default
  database: crm

cacti_db:
  <<: *default
  database: cacti

